export const MOCK_PROJECTS = [
    {
        id: "mock-cue-ai",
        title: "CUE AI",
        category: "Artificial Intelligence",
        isVisible: true,
        summary: "Advanced AI-powered conversational engine and reasoning system.",
        description: "A sophisticated AI platform leveraging large language models for deep contextual reasoning, semantic search, and intelligent automation workflows.",
        status: "Production",
        role: "Lead Architect",
        tags: ["Next.js", "Python", "FastAPI", "Vector DB", "Tailwind"],
        image: "/projects/cue_ai.png",
        demo: "#",
        github: "#",
        isFeatured: true,
        valuePoints: ["Deep contextual reasoning capabilities", "Vector-based semantic search", "Automated intelligent workflows"],
        metrics: ["Sub-500ms response time", "99.9% Uptime", "10k+ Daily Queries"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString()
    },
    {
        id: "mock-medq-ai",
        title: "MedQ AI",
        category: "Healthcare",
        isVisible: true,
        summary: "Next-gen healthcare data management with strictly audited clinical workflows.",
        description: "A secure medical record system (EMR) focusing on data privacy and rapid clinical data entry.",
        status: "Beta",
        role: "Backend Lead",
        tags: ["React.js", "MongoDB", "Express", "Node.js"],
        image: "/projects/medq_ai.png",
        demo: "https://gemini-med.vercel.app/",
        github: "https://github.com/kumail-kmr25/Que-med.git",
        isFeatured: true,
        valuePoints: ["Streamlined clinical documentation", "Predictive medical data entry", "HIPAA-compliant security framework"],
        metrics: ["Reduced entry time by 60%", "Zero data breaches", "Automated compliance checks"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString()
    },
    {
        id: "mock-edunova",
        title: "EduNova",
        category: "EdTech",
        isVisible: true,
        summary: "AI-powered learning platform for modern students and institutions.",
        description: "A comprehensive School Management System with 2FA, RBAC, and real-time institutional orchestration.",
        status: "Production",
        role: "Full Stack Architect",
        tags: ["Next.js", "Node.js", "PostgreSQL", "Prisma", "Tailwind"],
        image: "/projects/edunova.png",
        demo: "https://edunova-saas.vercel.app",
        github: "https://github.com/kumail-kmr25/Edunova-saas.git",
        isFeatured: false,
        valuePoints: ["Reduces administrative overhead by 40%", "Real-time student lifecycle management", "Secure institution-wide orchestration"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString()
    },
    {
        id: "mock-valekash",
        title: "ValeKash",
        category: "FinTech",
        isVisible: true,
        summary: "High-velocity fintech solution for seamless digital asset transactions and escrow.",
        description: "A secure payment processing and digital wallet platform focusing on transaction atomicity.",
        status: "Concept",
        role: "System Architect",
        tags: ["Next.js", "PostgreSQL", "Prisma", "Tailwind"],
        image: "/projects/valekash.png",
        demo: "https://valekash.vercel.app/",
        github: "https://github.com/kumail-kmr25/ValeKash-Final.git",
        isFeatured: false,
        valuePoints: ["Atomic digital asset transactions", "Automated escrow verification", "High-integrity financial ledger"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString()
    },
    {
        id: "mock-nestq-ai",
        title: "NESTQ AI",
        category: "FinTech",
        isVisible: true,
        summary: "AI-driven financial analytics engine for predictive budgeting and treasury management.",
        description: "An intelligent platform that uses machine learning to categorize expenses and predict future cash flow trends.",
        status: "Production",
        role: "Lead Developer",
        tags: ["React.js", "MongoDB", "Node.js", "Tailwind"],
        image: "/projects/finflow.png", // Reusing existing image placeholder
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["95% accurate cash-flow predictions", "Intelligent expense categorization", "SME financial optimization"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString()
    },
    {
        id: "mock-clinkart",
        title: "Clinkart",
        category: "E-Commerce",
        isVisible: true,
        summary: "High-performance E-commerce engine for modern retail and rapid scaling.",
        description: "A headless e-commerce solution with extreme focus on SEO, core web vitals, and conversion optimization.",
        status: "Production",
        role: "Full Stack Developer",
        tags: ["Next.js", "React.js", "MongoDB", "Tailwind"],
        image: "/projects/clinkart.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["100/100 Lighthouse performance", "Hyper-optimized conversion funnel", "Scalable headless commerce"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString()
    },
    {
        id: "mock-quebook",
        title: "Quebook",
        category: "Developer Tools",
        isVisible: true,
        summary: "Collaborative technical documentation platform for engineering-heavy teams.",
        description: "A documentation engine that supports markdown, live code samples, and complex system diagrams.",
        status: "Beta",
        role: "Frontend Engineer",
        tags: ["Next.js", "TypeScript", "MongoDB", "Tailwind"],
        image: "/projects/quebook.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["Real-time document sync", "Interactive system diagrams", "Markdown-first technical writing"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString()
    },
    {
        id: "mock-bab-e-ilm",
        title: "BAB E ILM",
        category: "Education",
        isVisible: true,
        summary: "Digital knowledge repository and comprehensive educational portal.",
        description: "A centralized platform for accessing structured educational content, featuring advanced search and categorizations.",
        status: "Production",
        role: "Full Stack Developer",
        tags: ["React.js", "Node.js", "PostgreSQL", "Tailwind"],
        image: "/projects/babeilm.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["Structured knowledge architecture", "Advanced semantic search", "Intuitive learning interfaces"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString()
    }
];
