export const MOCK_PROJECTS = [
    {
        id: "mock-1",
        title: "Edunova",
        isVisible: true,
        summary: "Enterprise-grade SaaS for academic orchestration and real-time institutional management.",
        description: "A comprehensive School Management System with 2FA, RBAC, and real-time notifications.",
        status: "Production",
        role: "Full Stack Architect",
        tags: ["TypeScript", "Next.js", "PostgreSQL", "Prisma", "Tailwind CSS"],
        image: "/projects/edunova.png",
        demo: "https://edunova-saas.vercel.app",
        github: "https://github.com/kumail-kmr25/Edunova-saas.git",
        isFeatured: true,
        valuePoints: ["Reduces administrative overhead by 40%", "Real-time student lifecycle management", "Secure institution-wide orchestration"],
        created_at: new Date().toISOString()
    },
    {
        id: "mock-2",
        title: "MedQ AI",
        isVisible: true,
        summary: "Next-gen healthcare data management with strictly audited clinical workflows.",
        description: "A secure medical record system (EMR) focusing on data privacy and rapid clinical data entry.",
        status: "Beta",
        role: "Backend Lead",
        tags: ["JavaScript", "React.js", "MongoDB", "Express", "Node.js"],
        image: "/projects/medq_ai.png",
        demo: "https://gemini-med.vercel.app/",
        github: "https://github.com/kumail-kmr25/Que-med.git",
        isFeatured: true,
        valuePoints: ["Streamlined clinical documentation", "Predictive medical data entry", "HIPAA-compliant security framework"],
        created_at: new Date().toISOString()
    },
    {
        id: "mock-3",
        title: "ValeKash",
        isVisible: true,
        summary: "High-velocity fintech solution for seamless digital asset transactions and escrow.",
        description: "A secure payment processing and digital wallet platform focusing on transaction atomicity.",
        status: "Concept",
        role: "System Architect",
        tags: ["TypeScript", "Next.js", "PostgreSQL", "Tailwind CSS"],
        image: "/projects/valekash.png",
        demo: "https://valekash.vercel.app/",
        github: "https://github.com/kumail-kmr25/ValeKash-Final.git",
        isFeatured: true,
        valuePoints: ["Atomic digital asset transactions", "Automated escrow verification", "High-integrity financial ledger"],
        created_at: new Date().toISOString()
    },
    {
        id: "mock-4",
        title: "FinFlow AI",
        isVisible: true,
        summary: "AI-driven financial analytics engine for predictive budgeting and treasury management.",
        description: "An intelligent platform that uses machine learning to categorize expenses and predict future cash flow trends.",
        status: "Production",
        role: "Lead Developer",
        tags: ["JavaScript", "React.js", "MongoDB", "Tailwind CSS"],
        image: "/projects/finflow.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["95% accurate cash-flow predictions", "Intelligent expense categorization", "SME financial optimization"],
        created_at: new Date().toISOString()
    },
    {
        id: "mock-5",
        title: "ClinkArt",
        isVisible: true,
        summary: "High-performance E-commerce engine for modern retail and rapid scaling.",
        description: "A headless e-commerce solution with extreme focus on SEO, core web vitals, and conversion optimization.",
        status: "Production",
        role: "Full Stack Developer",
        tags: ["JavaScript", "React.js", "MongoDB", "Next.js"],
        image: "/projects/clinkart.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["100/100 Lighthouse performance", "Hyper-optimized conversion funnel", "Scalable headless commerce"],
        created_at: new Date().toISOString()
    },
    {
        id: "mock-6",
        title: "QueBook",
        isVisible: true,
        summary: "Collaborative technical documentation platform for engineering-heavy teams.",
        description: "A documentation engine that supports markdown, live code samples, and complex system diagrams.",
        status: "Beta",
        role: "Frontend Engineer",
        tags: ["TypeScript", "Next.js", "MongoDB", "Framer Motion"],
        image: "/projects/quebook.png",
        demo: "#",
        github: "#",
        isFeatured: false,
        valuePoints: ["Real-time document sync", "Interactive system diagrams", "Markdown-first technical writing"],
        created_at: new Date().toISOString()
    }
];
