
export const highConversionProjects = [
    {
      id: "artisans-table",
      title: "The Artisan's Table",
      summary: "Custom Next.js storefront for a premium restaurant, replacing a static legacy site.",
      description: "Built a custom Next.js storefront with a 'Chef-First' visual narrative, integrated a low-overhead ordering system using Stripe, and implemented real-time table availability.",
      category: "Restaurant",
      status: "Production",
      role: "Lead Full-Stack Developer",
      tags: ["Next.js", "Tailwind", "Prisma", "Stripe"],
      image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Client had a beautiful physical location but a 2012-era static website with no ordering capability. Losing ~40% of leads to third-party apps.",
      solution: "Developed a bespoke e-commerce experience tailored for fine dining, focusing on visual conversion and seamless Stripe integration.",
      results: "+65% increase in direct online revenue; $1,200/mo saved in commission fees.",
      metrics: ["65% Revenue Growth", "98 Performance Score", "$1.2k Saved/mo"],
      isFeatured: true,
      isVisible: true,
      engineering: "Implemented a custom ISR strategy to keep menu prices live without sacrificing sub-second load times.",
      uiDepth: 95,
      backendDepth: 85,
      securityDepth: 90,
      scalabilityDepth: 80
    },
    {
      id: "azure-heights",
      title: "Azure Heights",
      summary: "Luxury boutique hotel booking engine designed to bypass OTA commissions.",
      description: "Premium, high-motion booking flow with immersive room galleries and 'Book Direct' loyalty perks.",
      category: "Hotel",
      status: "Production",
      role: "Full-Stack Architect",
      tags: ["Next.js", "Framer Motion", "Directus CMS", "PostgreSQL"],
      image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "OTA dependency (Booking/Expedia) was eating 20% of profits. Static site lacked trust and a clear direct-booking path.",
      solution: "Engineered a high-conversion booking engine that emphasizes direct-booking benefits and uses immersive cinematography.",
      results: "Direct bookings increased from 5% to 35% within 3 months.",
      metrics: ["35% Direct Bookings", "$15k Commission Saved", "4.9/5 UX Rating"],
      isFeatured: true,
      isVisible: true,
      engineering: "Built a custom persistent state machine for the booking flow to ensure zero data loss during multi-step guest registration.",
      uiDepth: 98,
      backendDepth: 80,
      securityDepth: 85,
      scalabilityDepth: 75
    },
    {
      id: "lumina-studio",
      title: "Lumina Studio",
      summary: "Cinema-grade cinematic portfolio for a high-end production agency.",
      description: "Agency portfolio with high-motion video reels, futuristic typography, and interactive video overlays.",
      category: "Agency",
      status: "Production",
      role: "Creative Developer",
      tags: ["Next.js", "Three.js", "GSAP", "Mux"],
      image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Agency portfolio felt 'flat' and didn't showcase their high-end video production quality.",
      solution: "Developed an immersive 'Digital Cinema' experience using advanced GSAP timelines and Three.js shader transitions.",
      results: "Signed two Fortune 500 clients within months of the new site launch.",
      metrics: ["2 High-Ticket Wins", "2.1s Video Load", "100% Client Sat"],
      isFeatured: true,
      isVisible: true,
      engineering: "Leveraged Mux for adaptive bitrate streaming, ensuring 4K quality on desktop while maintaining performance on 3G mobile devices.",
      uiDepth: 100,
      backendDepth: 60,
      securityDepth: 70,
      scalabilityDepth: 85
    },
    {
      id: "logiscale",
      title: "LogiScale",
      summary: "Enterprise supply chain analytics dashboard with proactive delay mitigation.",
      description: "Information-rich, heat-mapped dashboard for tracking logistics exceptions in real-time.",
      category: "SaaS",
      status: "Production",
      role: "Frontend Systems Lead",
      tags: ["React", "D3.js", "TailwindCSS", "TanStack Table"],
      image: "https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Legacy dashboard was a 'mess of tables' that overwhelmed users. Hard to find critical shipping delays.",
      solution: "Designed a 'Focus Mode' UI that uses heat-mapping to draw attention to high-risk exceptions automatically.",
      results: "30% reduction in average human response time to shipping exceptions.",
      metrics: ["30% Efficiency Gain", "Sub-sec Interaction", "Zero Config UI"],
      isFeatured: true,
      isVisible: true,
      engineering: "Optimized D3 rendering logic to handle 50,000+ data points in real-time without blocking the main UI thread.",
      uiDepth: 85,
      backendDepth: 95,
      securityDepth: 98,
      scalabilityDepth: 100
    },
    {
      id: "healthsync",
      title: "HealthSync",
      summary: "AI-driven patient onboarding MVP for a Series A healthcare startup.",
      description: "Modular Next.js app with secure data vaults and AI-driven intake forms.",
      category: "Startup",
      status: "Production",
      role: "MVP Developer",
      tags: ["Next.js", "AWS Bedrock", "Clerk", "PlanetScale"],
      image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Healthcare startup needed a HIPAA-compliant MVP in 6 weeks to secure Series A funding.",
      solution: "Rapidly deployed a modular architecture with zero-knowledge encryption for patient data and AI triage.",
      results: "Successfully raised $2.2M Seed Round using the MVP for demos.",
      metrics: ["6-Week Launch", "$2.2M Raised", "HIPAA Ready"],
      isFeatured: true,
      isVisible: true,
      engineering: "Implemented AWS Bedrock integration for intelligent triage with strict prompt-guardrail systems to ensure medical compliance.",
      uiDepth: 80,
      backendDepth: 90,
      securityDepth: 100,
      scalabilityDepth: 85
    },
    {
      id: "aura-essentials",
      title: "Aura Essentials",
      summary: "High-conversion D2C e-commerce platform for a premium skincare brand.",
      description: "Minimalist e-commerce with optimized mobile-first checkout and interactive skin-type quiz.",
      category: "E-commerce",
      status: "Production",
      role: "Conversion Specialist",
      tags: ["Next.js", "Shopify API", "Sanity.io", "Vercel"],
      image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Mobile cart abandonment was at 85%. Checkout feel was 'clunky.'",
      solution: "Engineered a 'one-tap' checkout flow and a personalized quiz to match products to skin types.",
      results: "Conversion rate jumped from 1.2% to 4.5% on mobile.",
      metrics: ["4.5% Conversion", "275% ROI", "92 PageSpeed"],
      isFeatured: true,
      isVisible: true,
      engineering: "Built a headless Shopify implementation to bypass liquid limitations, reducing time-to-interact by 70%.",
      uiDepth: 95,
      backendDepth: 75,
      securityDepth: 80,
      scalabilityDepth: 90
    },
    {
      id: "prime-estates",
      title: "Prime Estates",
      summary: "Map-centric property search platform for high-end real estate.",
      description: "Interactive real estate search UI with Mapbox integration and blazing-fast property filters.",
      category: "Real Estate",
      status: "Production",
      role: "UI/UX Developer",
      tags: ["Next.js", "MapBox", "Algolia", "Redis"],
      image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Users found it hard to visualize property locations relative to amenities. Listing pages were slow.",
      solution: "Developed a custom Mapbox engine that syncs in real-time with Algolia search results for instant feedback.",
      results: "10x increase in qualified buyer leads; average time on site +200%.",
      metrics: ["10x Leads", "3x Time-on-Site", "Sub-50ms Filter"],
      isFeatured: true,
      isVisible: true,
      engineering: "Implemented GeoJSON tiling for efficient map marker rendering, allowing 100,000+ points to remain buttery smooth.",
      uiDepth: 90,
      backendDepth: 85,
      securityDepth: 80,
      scalabilityDepth: 95
    },
    {
      id: "smokehouse",
      title: "The Smokehouse",
      summary: "High-performance BBQ ordering system with pit-temperature real-time tracking.",
      description: "Built a custom ordering UI tailored for mobile 'one-hand' operation and integrated a real-time marketing gimmick showing 'Pit Temperatures'.",
      category: "Restaurant",
      status: "Production",
      role: "Lead Full-Stack Developer",
      tags: ["Next.js", "Redis", "Framer Motion"],
      image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "High rejection rate on mobile due to complex menu structure and laggy interactions.",
      solution: "Streamlined the UI and implemented Redis-based caching for sub-50ms menu loads.",
      results: "+45% increase in repeat orders; Average order value up by 15%.",
      metrics: ["45% Repeat Rate", "15% AOV Growth", "99 Mobile Score"],
      isFeatured: false,
      isVisible: true,
      engineering: "Leveraged Redis Geo for proximity-based delivery calculations and Framer Motion for buttery-smooth menu transitions.",
      uiDepth: 88,
      backendDepth: 82,
      securityDepth: 75,
      scalabilityDepth: 80
    },
    {
      id: "green-fork",
      title: "Green Fork",
      summary: "Vegan meal-prep subscription engine with automated billing.",
      description: "Automated subscription engine with dynamic delivery routing and Stripe-managed billing cycles.",
      category: "Restaurant",
      status: "Production",
      role: "Lead Developer",
      tags: ["Next.js", "Stripe Billing", "PostgreSQL"],
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Manual subscription management was causing error rates in deliveries and missed payments.",
      solution: "Built a custom billing middleware that syncs Stripe events with a dynamic delivery dispatch system.",
      results: "Zero manual billing errors; 25% reduction in delivery labor costs.",
      metrics: ["Zero Errors", "25% Cost Cut", "1.1s TTI"],
      isFeatured: false,
      isVisible: true,
      engineering: "Implemented robust webhook handling with idiosyncratic idempotency keys to ensure zero double-billing.",
      uiDepth: 85,
      backendDepth: 92,
      securityDepth: 88,
      scalabilityDepth: 85
    },
    {
      id: "echo-lodge",
      title: "Echo Lodge",
      summary: "Minimalist cabin rental booking system with offline-first PWA capability.",
      description: "Highly accessible booking system designed for remote guests with fluctuating network signals.",
      category: "Hotel",
      status: "Production",
      role: "PWA Architect",
      tags: ["Next.js", "PWA", "Service Workers"],
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Guests in remote areas couldn't access their booking details or check-in maps without a signal.",
      solution: "Engineered a PWA with aggressive service-worker caching for all guest-facing itineraries.",
      results: "90% reduction in customer support calls for check-in info.",
      metrics: ["90% Support Drop", "Offline Ready", "100 SEO Score"],
      isFeatured: false,
      isVisible: true,
      engineering: "Custom background-sync implementation for checking availability updates even on edge connections.",
      uiDepth: 82,
      backendDepth: 78,
      securityDepth: 80,
      scalabilityDepth: 75
    },
    {
      id: "pixel-paper",
      title: "Pixel & Paper",
      summary: "Content-rich case study machine for a top-tier marketing agency.",
      description: "High-performance headless CMS implementation with extreme image optimization and SEO focus.",
      category: "Agency",
      status: "Production",
      role: "Frontend Lead",
      tags: ["Next.js", "Sanity CMS", "Vercel"],
      image: "https://images.unsplash.com/photo-1454165833767-027ffea9e77b?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Slow legacy WordPress site was destroying their lighthouse scores and SEO ranking.",
      solution: "Rebuilt the entire engine as a static Next.js app with Sanity as the content backbone.",
      results: "Jumped from page 4 to page 1 on Google for target keywords.",
      metrics: ["Page 1 Google", "95+ Core Web Vitals", "400% Traffic Increase"],
      isFeatured: false,
      isVisible: true,
      engineering: "Implemented next/image for automatic WebP conversion and tiered ISR for instant content updates.",
      uiDepth: 95,
      backendDepth: 65,
      securityDepth: 70,
      scalabilityDepth: 80
    },
    {
      id: "nova-ai",
      title: "Nova AI",
      summary: "AI-powered internal developer documentation search tool.",
      description: "RAG-driven search engine that indexes internal company documentation for instant retrieval.",
      category: "Startup",
      status: "Production",
      role: "AI Developer",
      tags: ["Next.js", "OpenAI", "Pinecone"],
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Engineering teams were wasting 10+ hours a week searching through fragmented PDF documentation.",
      solution: "Developed a semantic search tool using OpenAI embeddings stored in a Pinecone vector DB.",
      results: "Average search time reduced from 12 minutes to 4 seconds.",
      metrics: ["4s Search Speed", "98% Accuracy", "AI Integrated"],
      isFeatured: false,
      isVisible: true,
      engineering: "Custom PDF parsing logic that preserves document context for more accurate vector embeddings.",
      uiDepth: 80,
      backendDepth: 95,
      securityDepth: 90,
      scalabilityDepth: 88
    },
    {
      id: "invoicely",
      title: "Invoicely",
      summary: "Collaborative invoicing tool for creative freelancer teams.",
      description: "A centralized dashboard for tracking, sending, and automating creative service payments.",
      category: "SaaS",
      status: "Production",
      role: "Full-Stack Developer",
      tags: ["React", "Prisma", "Zod", "Tailwind"],
      image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Freelancers were losing thousands due to unpaid invoices lost in email chaos.",
      solution: "Unified platform with real-time 'Read Receipts' and automated follow-up sequences.",
      results: "30% faster payment cycles; $0 in lost unpaid invoices.",
      metrics: ["30% Faster Pay", "Zero Lost Rev", "Bank Grade Security"],
      isFeatured: false,
      isVisible: true,
      engineering: "Implemented Zod-based validation across the entire stack to ensure data integrity for multi-currency invoicing.",
      uiDepth: 85,
      backendDepth: 88,
      securityDepth: 95,
      scalabilityDepth: 90
    },
    {
      id: "dr-clean",
      title: "Dr. Clean",
      summary: "Interactive lead-gen estimator for a premium cleaning service.",
      description: "Conversion-optimized intake system that pre-qualifies local service leads via an interactive quiz.",
      category: "Local Service",
      status: "Production",
      role: "Conversion Lead",
      tags: ["Next.js", "React Hook Form", "Resend"],
      image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Generic 'Contact Us' forms had a dismal 2% conversion rate and generated low-quality leads.",
      solution: "Designed a multi-step 'Price Estimator' that pre-qualifies users before they ever submit their info.",
      results: "Conversion rate increased to 18%; 150+ new monthly leads.",
      metrics: ["18% Conversion", "150 Leads/mo", "Premium UX"],
      isFeatured: false,
      isVisible: true,
      engineering: "Built a custom form-builder logic that allows the client to update pricing factors without code changes.",
      uiDepth: 92,
      backendDepth: 70,
      securityDepth: 75,
      scalabilityDepth: 70
    },
    {
      id: "sparky-pro",
      title: "Sparky Pro",
      summary: "Real-time emergency electrician dispatch system.",
      description: "Automated alert and routing system for emergency electrical service calls.",
      category: "Local Service",
      status: "Production",
      role: "Lead Architect",
      tags: ["Next.js", "Twilio", "Upstash"],
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Emergency calls were being missed during off-hours, leading to $5k+ monthly revenue loss.",
      solution: "Integrated Twilio for automated phone/SMS alerts and Upstash for serverless state management.",
      results: "Response time dropped from 4 hours to 45 minutes.",
      metrics: ["45m Response", "15% More Calls", "Twilio Integrated"],
      isFeatured: false,
      isVisible: true,
      engineering: "Implementation of a 'Dead-Man-Switch' alert logic to ensure calls are escalated if not answered by the first tech.",
      uiDepth: 75,
      backendDepth: 90,
      securityDepth: 80,
      scalabilityDepth: 85
    },
    {
      id: "retro-beats",
      title: "Retro Beats",
      summary: "High-fidelity vinyl marketplace with audio-preview integration.",
      description: "Immersive e-commerce experience for audiophiles with Spotify-authenticated previewing.",
      category: "E-commerce",
      status: "Production",
      role: "Creative Developer",
      tags: ["Next.js", "Spotify API", "Framer Motion"],
      image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=1200",
      demo: "#",
      problem: "Users wouldn't buy rare, expensive records without hearing a high-fidelity preview first.",
      solution: "Custom audio-bridge using Spotify API and high-resolution visuals of actual record condition.",
      results: "+80% increase in checkout completions for rare collection items.",
      metrics: ["80% Checkout Lift", "Audio Syncing", "92 Mobile UX"],
      isFeatured: false,
      isVisible: true,
      engineering: "Advanced Framer Motion orchestration for a 'Tactile' experience that mimics flipping through physical record crates.",
      uiDepth: 98,
      backendDepth: 75,
      securityDepth: 80,
      scalabilityDepth: 85
    }
];
