-- Hide existing projects
UPDATE "Project" SET "isVisible" = false, "isFeatured" = false;

-- Insert/Update projects
-- 1. EDUNOVA
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'EDUNOVA - SCHOOL MANAGEMENT SYSTEM', 'Comprehensive academic governance and student lifecycle management platform.', 'A high-performance system designed to streamline school operations, from admissions and attendance to grading and parent communication. Features a robust real-time dashboard for administrators.', 'Production', 'Full Stack Lead', ARRAY['Next.js', 'PostgreSQL', 'Prisma', 'Real-time Analytics'], '/projects/edunova.png', 'https://edunova-demo.vercel.app', 'https://github.com/kumail-kmr25/edunova', 'EdTech', true, 'Schools struggled with fragmented data, manual attendance tracking, and delayed communication between teachers and parents, leading to administrative inefficiency.', 'Implemented a centralized database with real-time sync, automated attendance via QR codes, and an integrated portal for instant parent-teacher interaction.', ARRAY['40% reduction in manual paperwork', 'Real-time student progress tracking', 'Secure cloud-based data storage'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 2. MedQ AI
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'MedQ AI - HEALTHCARE MANAGEMENT SYSTEM', 'AI-driven clinical workflow optimization and patient care platform.', 'An advanced healthcare system integrating AI for diagnostic assistance, automated scheduling, and secure electronic health records (EHR). Designed for modern clinics and hospitals.', 'Beta', 'AI Systems Architect', ARRAY['AI/ML', 'Next.js', 'Node.js', 'Docker'], '/projects/medq_ai.png', 'https://medq-ai.vercel.app', 'https://github.com/kumail-kmr25/medq-ai', 'HealthTech', true, 'Healthcare providers were overwhelmed by administrative tasks and lacked intelligent tools to assist in rapid patient diagnosis and scheduling optimization.', 'Integrated machine learning models for predictive diagnostics and a smart scheduling algorithm that reduced patient wait times by 25%.', ARRAY['AI diagnostic assistance', 'Automated patient scheduling', 'HIPAA-compliant data handling'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 3. CUE AI
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'CUE AI - PERSONAL ASSISTANT CHATBOT', 'Next-generation AI assistant for workflow automation and query resolution.', 'A sophisticated AI chatbot that acts as a personal assistant, solving complex queries, automating repetitive tasks, and integrating with productivity tools to accelerate workflow.', 'Production', 'Lead Developer', ARRAY['LLM', 'OpenAI API', 'Vector DB', 'React'], '/projects/cue_ai.png', 'https://cue-ai.vercel.app', 'https://github.com/kumail-kmr25/cue-ai', 'AI & Productivity', true, 'Professionals lose significant time searching for information across various tools and performing redundant manual tasks.', 'Developed a context-aware chatbot using RAG (Retrieval-Augmented Generation) to provide instant, accurate answers and automate cross-platform tasks.', ARRAY['Instant query resolution', 'Task automation workflows', 'Context-aware conversations'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 4. VALEKASH
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'VALEKASH - COMPREHENSIVE KASHMIR SYSTEM', 'Regional digital infrastructure for services, tourism, and community management.', 'A dedicated platform for the Kashmir region, integrating local government services, tourism resources, and business directories into a single, user-friendly digital ecosystem.', 'Production', 'Full Stack Developer', ARRAY['Next.js', 'Mapbox', 'Local SEO', 'Serverless'], '/projects/valekash.png', 'https://valekash.com', 'https://github.com/kumail-kmr25/valekash', 'GovTech / Regional', false, 'Lack of a unified digital platform for local services and tourism in Kashmir led to information silos and poor accessibility for both residents and visitors.', 'Created a centralized hub with interactive maps, service directories, and cultural resources, significantly boosting regional digital engagement.', ARRAY['Unified regional service hub', 'Interactive tourism mapping', 'Local business ecosystem support'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 5. CLINKART
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'CLINKART - AI-POWERED E-COMMERCE', 'High-fashion marketplace with intelligent recommendation engines.', 'A unique e-commerce platform that leverages AI algorithms to suggest products based on user behavior and style preferences. Features a premium, cinematic shopping interface.', 'Beta', 'E-commerce Specialist', ARRAY['Recommendation Engine', 'Tailwind CSS', 'Stripe', 'Next.js'], '/projects/clinkart.png', 'https://clinkart.shop', 'https://github.com/kumail-kmr25/clinkart', 'E-commerce', false, 'Standard e-commerce platforms often fail to provide personalized shopping experiences, leading to lower conversion rates in niche markets.', 'Implemented a behavior-based recommendation engine and a premium UI to enhance user engagement and drive personalized sales.', ARRAY['AI-driven product discovery', 'Premium cinematic UI/UX', 'Seamless secure payments'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 6. QUANT AI
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'QUANT AI - FINANCE & MANAGEMENT SYSTEM', 'Enterprise-grade financial intelligence and accounting tool.', 'A complete management solution for finance and accounting, providing deep insights, automated reporting, and AI-driven fiscal projections for businesses.', 'Beta', 'Fintech Engineer', ARRAY['Data Visualization', 'Fintech', 'GraphQL', 'Python'], '/projects/quant_ai.png', 'https://quant-ai.finance', 'https://github.com/kumail-kmr25/quant-ai', 'Fintech', false, 'Traditional accounting software is often too rigid or complex, making it difficult for businesses to gain real-time fiscal insights and accurate projections.', 'Built a flexible, AI-powered dashboard that automates complex financial reports and provides predictive modeling for better decision-making.', ARRAY['Automated fiscal reporting', 'Predictive financial modeling', 'Real-time budget tracking'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 7. QUEBOOK
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'QUEBOOK - AI SOCIAL MEDIA PLATFORM', 'Next-gen community platform with smart content categorization.', 'An AI-powered social media network designed for meaningful interactions, featuring intelligent content filtering, community-driven features, and high user privacy.', 'Concept', 'Social Systems Architect', ARRAY['WebSockets', 'NoSQL', 'AI Moderation', 'Next.js'], '/projects/quebook.png', 'https://quebook.app', 'https://github.com/kumail-kmr25/quebook', 'Social Tech', false, 'Modern social platforms are often cluttered with irrelevant content and suffer from poor community moderation.', 'Designed an AI categorization engine that prioritizes relevant discussions and provides automated, fair content moderation.', ARRAY['Smart content categorization', 'AI-driven community moderation', 'Privacy-first architecture'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();

-- 8. MYTRIPZ
INSERT INTO "Project" (id, title, summary, description, status, role, tags, image, demo, github, category, "isFeatured", problem, solution, "valuePoints", "isVisible", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'MYTRIPZ - TRAVEL & BOOKING APP', 'Consolidated booking platform for travel, hotels, and dining.', 'A comprehensive travel companion app that integrates flights, hotel stays, and restaurant reservations into a single, seamless booking experience.', 'Production', 'Product Engineer', ARRAY['Mobile First', 'Booking APIs', 'Google Maps', 'React Native'], '/projects/mytripz.png', 'https://mytripz.travel', 'https://github.com/kumail-kmr25/mytripz', 'TravelTech', false, 'Travelers struggle with managing multiple apps for different parts of their journey, leading to fragmented itineraries and stress.', 'Unified the entire travel lifecycle into one app, providing synchronized bookings and real-time updates for every stage of the trip.', ARRAY['Unified travel itinerary', 'One-tap multi-service booking', 'Real-time travel alerts'], true, NOW(), NOW())
ON CONFLICT (title) DO UPDATE SET
summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, role = EXCLUDED.role, tags = EXCLUDED.tags, image = EXCLUDED.image, demo = EXCLUDED.demo, github = EXCLUDED.github, category = EXCLUDED.category, "isFeatured" = EXCLUDED."isFeatured", problem = EXCLUDED.problem, solution = EXCLUDED.solution, "valuePoints" = EXCLUDED."valuePoints", "isVisible" = true, "updated_at" = NOW();
