import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

import * as route_admin_active_projects_route_ts from './api/admin/active-projects/route';
app.get('/api/admin/active-projects', route_admin_active_projects_route_ts.GET);
app.post('/api/admin/active-projects', route_admin_active_projects_route_ts.POST);
import * as route_admin_active_projects__id__route_ts from './api/admin/active-projects/[id]/route';
app.delete('/api/admin/active-projects/:id', route_admin_active_projects__id__route_ts.DELETE);
app.patch('/api/admin/active-projects/:id', route_admin_active_projects__id__route_ts.PATCH);
import * as route_admin_availability_route_ts from './api/admin/availability/route';
app.patch('/api/admin/availability', route_admin_availability_route_ts.PATCH);
import * as route_admin_case_studies_route_ts from './api/admin/case-studies/route';
app.get('/api/admin/case-studies', route_admin_case_studies_route_ts.GET);
app.post('/api/admin/case-studies', route_admin_case_studies_route_ts.POST);
import * as route_admin_case_studies__id__route_ts from './api/admin/case-studies/[id]/route';
app.delete('/api/admin/case-studies/:id', route_admin_case_studies__id__route_ts.DELETE);
app.patch('/api/admin/case-studies/:id', route_admin_case_studies__id__route_ts.PATCH);
import * as route_admin_contact__id__route_ts from './api/admin/contact/[id]/route';
app.delete('/api/admin/contact/:id', route_admin_contact__id__route_ts.DELETE);
app.patch('/api/admin/contact/:id', route_admin_contact__id__route_ts.PATCH);
import * as route_admin_diagnostic_logs_route_ts from './api/admin/diagnostic-logs/route';
app.get('/api/admin/diagnostic-logs', route_admin_diagnostic_logs_route_ts.GET);
import * as route_admin_diagnostic_patterns_route_ts from './api/admin/diagnostic-patterns/route';
app.get('/api/admin/diagnostic-patterns', route_admin_diagnostic_patterns_route_ts.GET);
app.post('/api/admin/diagnostic-patterns', route_admin_diagnostic_patterns_route_ts.POST);
import * as route_admin_diagnostic_patterns__id__route_ts from './api/admin/diagnostic-patterns/[id]/route';
app.delete('/api/admin/diagnostic-patterns/:id', route_admin_diagnostic_patterns__id__route_ts.DELETE);
app.patch('/api/admin/diagnostic-patterns/:id', route_admin_diagnostic_patterns__id__route_ts.PATCH);
import * as route_admin_feature_requests_route_ts from './api/admin/feature-requests/route';
app.get('/api/admin/feature-requests', route_admin_feature_requests_route_ts.GET);
import * as route_admin_feature_requests__id__route_ts from './api/admin/feature-requests/[id]/route';
app.patch('/api/admin/feature-requests/:id', route_admin_feature_requests__id__route_ts.PATCH);
import * as route_admin_hire_route_ts from './api/admin/hire/route';
app.get('/api/admin/hire', route_admin_hire_route_ts.GET);
app.patch('/api/admin/hire', route_admin_hire_route_ts.PATCH);
import * as route_admin_hire_stats_route_ts from './api/admin/hire/stats/route';
app.get('/api/admin/hire/stats', route_admin_hire_stats_route_ts.GET);
import * as route_admin_hire__id__route_ts from './api/admin/hire/[id]/route';
app.delete('/api/admin/hire/:id', route_admin_hire__id__route_ts.DELETE);
import * as route_admin_login_route_ts from './api/admin/login/route';
app.post('/api/admin/login', route_admin_login_route_ts.POST);
import * as route_admin_logout_route_ts from './api/admin/logout/route';
app.post('/api/admin/logout', route_admin_logout_route_ts.POST);
import * as route_admin_register_route_ts from './api/admin/register/route';
app.get('/api/admin/register', route_admin_register_route_ts.GET);
app.post('/api/admin/register', route_admin_register_route_ts.POST);
import * as route_admin_reset_password_route_ts from './api/admin/reset-password/route';
app.post('/api/admin/reset-password', route_admin_reset_password_route_ts.POST);
import * as route_admin_stats_route_ts from './api/admin/stats/route';
app.patch('/api/admin/stats', route_admin_stats_route_ts.PATCH);
import * as route_admin_system_config_route_ts from './api/admin/system-config/route';
app.get('/api/admin/system-config', route_admin_system_config_route_ts.GET);
app.patch('/api/admin/system-config', route_admin_system_config_route_ts.PATCH);
import * as route_admin_testimonials_route_ts from './api/admin/testimonials/route';
app.get('/api/admin/testimonials', route_admin_testimonials_route_ts.GET);
app.patch('/api/admin/testimonials', route_admin_testimonials_route_ts.PATCH);
import * as route_availability_route_ts from './api/availability/route';
app.get('/api/availability', route_availability_route_ts.GET);
import * as route_blog_route_ts from './api/blog/route';
app.get('/api/blog', route_blog_route_ts.GET);
app.post('/api/blog', route_blog_route_ts.POST);
import * as route_blog__id__route_ts from './api/blog/[id]/route';
app.delete('/api/blog/:id', route_blog__id__route_ts.DELETE);
app.patch('/api/blog/:id', route_blog__id__route_ts.PATCH);
import * as route_case_studies_route_ts from './api/case-studies/route';
app.get('/api/case-studies', route_case_studies_route_ts.GET);
import * as route_contact_route_ts from './api/contact/route';
app.get('/api/contact', route_contact_route_ts.GET);
app.post('/api/contact', route_contact_route_ts.POST);
app.put('/api/contact', route_contact_route_ts.PUT);
app.delete('/api/contact', route_contact_route_ts.DELETE);
import * as route_diagnose_route_ts from './api/diagnose/route';
app.post('/api/diagnose', route_diagnose_route_ts.POST);
import * as route_feature_requests_route_ts from './api/feature-requests/route';
app.get('/api/feature-requests', route_feature_requests_route_ts.GET);
app.post('/api/feature-requests', route_feature_requests_route_ts.POST);
import * as route_forgot_password_route_ts from './api/forgot-password/route';
app.post('/api/forgot-password', route_forgot_password_route_ts.POST);
import * as route_hire_route_ts from './api/hire/route';
app.get('/api/hire', route_hire_route_ts.GET);
app.post('/api/hire', route_hire_route_ts.POST);
import * as route_projects_route_ts from './api/projects/route';
app.get('/api/projects', route_projects_route_ts.GET);
app.post('/api/projects', route_projects_route_ts.POST);
import * as route_projects__id__route_ts from './api/projects/[id]/route';
app.delete('/api/projects/:id', route_projects__id__route_ts.DELETE);
app.patch('/api/projects/:id', route_projects__id__route_ts.PATCH);
import * as route_stats_route_ts from './api/stats/route';
app.get('/api/stats', route_stats_route_ts.GET);
import * as route_testimonials_route_ts from './api/testimonials/route';
app.get('/api/testimonials', route_testimonials_route_ts.GET);
app.post('/api/testimonials', route_testimonials_route_ts.POST);
import * as route_testimonials__id__route_ts from './api/testimonials/[id]/route';
app.delete('/api/testimonials/:id', route_testimonials__id__route_ts.DELETE);
app.patch('/api/testimonials/:id', route_testimonials__id__route_ts.PATCH);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log('Backend listening on port ' + PORT));
